# Generated by Django 2.2.6 on 2019-11-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoge',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoges', to='todo_list.Customer'),
        ),
    ]
